[build]
  command = "pnpm run build"
  functions = "dist"
  publish = "dist/public"

[dev]
  command = "pnpm run dev"
  port = 3000

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
